train:
  _target_: src.datasets.MediaEvalDataset
  part: "train"
  split: 0.99
  data_dir: "../dataset"
  limit: 512
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.MediaEvalDataset
  part: "val"
  split: ${datasets.train.split}
  data_dir: "../dataset"
  limit: 512
  instance_transforms: ${transforms.instance_transforms.inference}
