train:
  _target_: src.datasets.MediaEvalDataset
  part: "train"
  split: 0.99
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.MediaEvalDataset
  part: "val"
  split: ${datasets.train.split}
  instance_transforms: ${transforms.instance_transforms.inference}
