train: []
val: []
inference:
  - _target_: src.metrics.ThresholdMetric
    name: "Accuracy_1_km"
    threshold: 1
  - _target_: src.metrics.ThresholdMetric
    name: "Accuracy_25_km"
    threshold: 25
  - _target_: src.metrics.ThresholdMetric
    name: "Accuracy_200_km"
    threshold: 200
  - _target_: src.metrics.ThresholdMetric
    name: "Accuracy_750_km"
    threshold: 750
  - _target_: src.metrics.ThresholdMetric
    name: "Accuracy_2500_km"
    threshold: 2500
