defaults:
  - model: geoclip
  - writer: wandb
  - metrics: main
  - datasets: train
  - dataloader: main
  - transforms: main
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-5
  weight_decay: 1e-6

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.87
  step_size: 1
loss_function:
  _target_: src.loss.CrossEntropyLossWrapper
trainer:
  log_step: 50
  n_epochs: 10
  device_tensors: ["images", "locations", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "min val_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: ${trainer.n_epochs} # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
